sudo: required
dist: xenial
cache:
  directories:
    - "$HOME/.pip-cache/"
    - ".tox"
language: python
python:
  - "3.6"
services:
  - docker
install:
  - pip install --upgrade pip
  - pip install tox==3.13.2
  - pip install python-coveralls
env:
  matrix:
    - TOX_ENV=python
    - TOX_ENV=flake8
    - TOX_ENV=docs
before_script:
  # Use a specific SHA of MBL as the E+ FMU seems to be causing issues in more recent commits
  - |
    git clone --single-branch --branch issue1437_district_heating_cooling https://github.com/lbl-srg/modelica-buildings.git
    export MODELICAPATH=$(pwd)/modelica-buildings
    cd $MODELICAPATH
    echo $(git branch)
script:
  - tox -e $TOX_ENV
after_success:
  - coveralls
after_failure:
  - echo "Job Failed... Maybe these logs will help?"
  - free -tm
  - ls -alt /home/travis/build/urbanopt/geojson-modelica-translator
  - echo "============================================ stdout.log ========================================="
  - |
    find /home/travis/build/urbanopt/geojson-modelica-translator -type f -name 'stdout.log' -print | while read filename; do
      echo "$filename"
      cat "$filename"
    done
